### ISSUE TITLE
deploy a complicated erc20 contract, i can't get the right balance :(

### ISSUE THREAD

**Issue by caivega** [MOACChain/moac-core#6] opened 2018-04-11 02:59 UTC
after i deployed the contract, with the gasLimit which is estimated by following code,

`
  var gasEstimate = chain3.mc.estimateGas({data: bytecode});
`
returned successfully,
`
succeed:  0x126984b461882a8310c1c181cd13cb7d55dc5cba5780da633966322caa6bf350
`
the hash of the deployed transaction is 0x126984b461882a8310c1c181cd13cb7d55dc5cba5780da633966322caa6bf350, 
and the address of the contract is 0xb81cab506c68f3938f8ce9c15c1f699b51669565,
and the address that deployed the contract is 0xdf1af7a1bde662f32e9d9765991baa5172125bff.

the problem is that, when i call the balanceOf method of the erc20 contract with the parameter that is the owner's address, it should be the total coin of the erc20 coin, however it returns 
the zero,
`
{ [String: '0'] s: 1, e: 0, c: [ 0 ] }
`

anyone can help me?

**Comment by mdranger** [comment] 2018-04-11 03:26
We found out for this version of the testnet, the gasLimit for deploying a contract set to normal value will cause some issues of the results. Please increase the gasLimit to a high amount, such as 10 times of the estimates. Don't panic, the actual cost of the gas is still the same. Extra gas will be returned to your account after deploy. We are working on this issues and will fix it in the coming release. 
Thanks very much.

**Comment by mdranger** [comment] 2018-04-18 13:53
The issue is fixed in the new release 0.8.1. The estimate of gasLimit to deploy a contract is not accurate and can be lower than really needed. In previous version, if the allowed gasLimit is not enough, the TX will be added without the data. That's why you got a returned HASH but not contract is available. In this new version, we let the TX fail if the data cannot be added. However, =we suggested to add enough gasLimit to be safe to deploy the contract, such as 2 times of the gasLimit as precalculated. Thanks.

**Closed by mdranger** 2018-04-18 13:53 UTC

**Comment by caivega** [comment] 2018-04-18 15:57
thx,:)
